### ISSUE TITLE
Exec Circle Highlights

### ISSUE THREAD

**Issue by ratstache** [umdevclub/devClub#1]
## Problem
The highlights on the exec pictures are a nice effect but it doesn't highlight when hovering over the title of the exec or the yellow area surrounding the text

**When hovering over the image or circle**
![image](https://user-images.githubusercontent.com/8846353/27569443-4a5e7e5a-5abd-11e7-966a-12fb8c0b2283.png)

**When hovering over the text or yellow part** (sorry Alex :stuck_out_tongue: )
![image](https://user-images.githubusercontent.com/8846353/27569467-6c88b978-5abd-11e7-9761-a0ac3eff4fc5.png)

## Fix
Ideally we would want this to highlight when we hover over the text and yellow area. Additionally we would like the cursor to remain an arrow rather than a text cursor when hovering over the text here.

**Comment by Nicolasome** [comment]
I spent a long time trying to figure out how to solve this issue with CSS which would be my preferred method but couldn't get it working.  I'll attempt with JQuerry shortly.

The last part of the problem (keeping the cursor as an arrow when hovering over text) can easily be achieved with CSS though,  I got it working with the following
```
#execs span.title:hover{
    cursor: default;
}
```

**Comment by ratstache** [comment]
Hey, thanks for taking a look at this. I think if we move the span inside of the same div that the image is in we can do a hover on the div instead of the span.

I think it would look something like this:

```
<div id="exec_img">
    <img src="whatever" id="(some_image_identifier)" alt="Landon">
    <span class="Title">(executive position name)</span>
</div>
```

with the css something like:
```
#exec_img:hover > (some_image_identifier) {
    (Whatever effect is already on the img)
}
```

actually I'm not even sure we would have to move the span if we did this.

Would you mind taking a look at it? And making the change to the cursor that you suggested?

If it's really not feasible and you think jquery is a better route I'm game for that too.

**Comment by Nicolasome** [comment]
I'm probably going to put this issue on halt for a while.

This is what I found out:
It definately is possible to do it with css/html but here's the catch:

The problem: There is no simple way of selecting a "previous sibling" in CSS.
Solution: Declare the title before the img using sorcery.

There is two potential method I got "working" albeit in an very ugly fashion.

1. 
HTML
```
                <span class="title">Co-President</span>
                <div class="exec_img">
                    <img src="images/alex.jpg" alt="Alex" />
                </div>
```
                    
CSS:
```
#execs span.title:hover+img{
    border: 15px solid rgba(0, 77, 153, .5) ;
    position: relative;
    transition: all 0.1s ease-in;
}
```

The Issue I wasen't able to fix:
![image](https://user-images.githubusercontent.com/8783674/36345724-ec35815a-13f5-11e8-9540-6bebe3aa5ebf.png)

2.
Use flexbox (display: flex;) as described [here](https://stackoverflow.com/questions/1817792/is-there-a-previous-sibling-css-selector/36118012#36118012):

I tried using the `<ul> `method and got it working! But I wasen't able to re-align the elements correctly.

.
.
.
I wasen't able to get ratstache suggestion working.
The issue with using the child method like ratstache sugested, is that the img will glow even when the pointer isin't on the img.  It's a minor issue but something that would trigger my OCD.


.
The last part of the issue:
> Additionally we would like the cursor to remain an arrow rather than a text cursor when hovering over the text here.

Can be fixed using this CSS:
```
#execs span.title:hover{
    cursor: default;
}
```

If someone gets this working, I'll be super stoked.

**Comment by ratstache** [comment]
Ah yes, you're right. When I had pictured that working I thought it would be fine for the image to highlight when the user moved onto that div but it would be better if it was limited to the image and the text. 

Let's put this one on ice for a bit and hope a hero comes along :P. Thanks for looking at it, it will definitely make it easier for the next person who picks it up!
