### ISSUE TITLE
Update the Copy

### ISSUE THREAD

**Issue by ratstache** [umdevclub/devClub#2]
## Problem
The copy is a great placeholder but it needs to be updated. There are some spelling mistakes and grammatical errors that need to be fixed before the fall.

## Fix
We should have a discussion about what we want to communicate to people who visit the site and spend some time writing a copy we can be proud of.

**Comment by Nandob777** [comment]
@ratstache fall has come and gone, and we have some fixes implemented.  Would you mind if we closed this issue?  We should check to see if this is still an issue and possibly make a new more up-to-date one

**Comment by ratstache** [comment]
I still think it needs to be reworked but we can close for now.
